import Head from "next/head";
import Layout from "../components/Layout";
import Services from "../components/Services";
import Featured from "../components/Featured";

export default function Home() {
  return (
    <Layout>
      <div>
        <Head>
          <title>Pie</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/Logo.png"  />
        </Head>
        <Featured/>
        <Services/>
        {/* body */}
       
       
      </div>
     
      </Layout>
  );
}

export const getServerSideProps = async()=> {
  
}
