import Head from "next/head";
import Layout from "../components/Layout";
import Services from "../components/Services";
import Featured from "../components/Featured";
import { client } from "../lib/client";
import Menu from "../components/Menu";

export default function Home({pizzas}) {
  // console.log(pizzas);
  return (
    <Layout>
      <div>
        <Head>
          <title>Pie</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/Logo.png"  />
        </Head>
        <Featured/>
        <Services/>
        <Menu pizzas={pizzas}/>
        {/* body */}
       
       
      </div>
     
      </Layout>
  );
}

export const getServerSideProps = async()=> {
  const query = '*[_type == "pizza"]';
  const pizzas = await client.fetch(query);
  return {
    props: {
      pizzas
    }
  }
}
